storage_adapters:
  satbased.security.profile:
    class: Daikon\CouchDb\Storage\CouchDbStorageAdapter
    connector: satbased.security.event_store
    settings:
      design_doc: satbased-security-profile

stream_stores:
  satbased.security.profile:
    class: Daikon\CouchDb\Storage\CouchDbStreamStorage
    storage_adapter: satbased.security.profile

units_of_work:
  satbased.security.profile:
    class: Daikon\EventSourcing\EventStore\UnitOfWork
    stream_store: satbased.security.profile
    aggregate_root: Satbased\Security\Profile\Profile