version: "3.2"

volumes:
  couchdb_data:
  elasticsearch_data:

services:
  proxy:
    environment:
      NGINX_REDIRECT_PORT80: "true"
      SERVER1HTTPS_ENABLED: "true"
      SERVER1HTTP_ENABLED: "false"
      SERVER1CERTIFICATE_DNAME: "/CN=NGUtech/OU=Satbased/O=${APP_DOMAIN}/L=LOCAL/C=XY"

  nginx:
    volumes:
      - ../..:/var/www

  php:
    volumes:
      - ../..:/var/www

  couchdb:
    volumes:
      - couchdb_data:/opt/couchdb/data

  elasticsearch:
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - node.name=${APP_HOST}
      - transport.host=127.0.0.1
      - http.host=0.0.0.0
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=Authorization
      - xpack.security.enabled=true
      - xpack.watcher.enabled=false
      - ELASTIC_PASSWORD
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  kibana:
    container_name: ${COMPOSE_PROJECT_NAME}_kibana
    image: docker.elastic.co/kibana/kibana:7.11.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_URL=http://elasticsearch:9200
