Satbased\Security\Entity\VerificationToken:
  exclusion_policy: ALL
  discriminator:
    field_name: '@type'
    map:
      Satbased\Security\Entity\VerificationToken: Satbased\Security\Entity\VerificationToken
  virtual_properties:
    getId:
      type: ValueObject
    getToken:
      type: ValueObject
    getExpiresAt:
      type: ValueObject